Repository AY1920S1-CS2103T-T13-2/main, pull requests merged in 2019-10, with the labels that each got.

#22 Change UserGuide to the Mortago UserGuide
  docs/UserGuide.adoc
  docs/images/Ui.png
Labels: morphing

#23 [tutorial-adding-command] Add remark command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: tutorial

#9 Implement Body Class & Unit Tests
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/model/entity/PhoneNumber.java
  src/main/java/seedu/address/model/entity/Sex.java
  src/main/java/seedu/address/model/entity/body/Body.java
  src/main/java/seedu/address/model/entity/body/Nric.java
  src/main/java/seedu/address/model/entity/body/Religion.java
  src/main/java/seedu/address/model/entity/body/Status.java
  src/test/java/seedu/address/model/entity/body/BodyTest.java
  src/test/java/seedu/address/model/entity/body/NricTest.java
  src/test/java/seedu/address/model/entity/body/PhoneNumberTest.java
  src/test/java/seedu/address/model/entity/body/ReligionTest.java
  src/test/java/seedu/address/model/entity/body/SexTest.java
  src/test/java/seedu/address/model/entity/body/StatusTest.java
  src/test/java/seedu/address/testutil/BodyBuilder.java
  src/test/java/seedu/address/testutil/TypicalBodies.java
  unused/BodyIdentificationNumber.java
  unused/BodyIdentificationNumberTest.java
Labels: feature, morphing

#48 [entity-class-body] Change the variable name BodyIdentificationNumber to BodyIdNum
  src/main/java/seedu/address/model/entity/body/Body.java
  src/test/java/seedu/address/model/entity/body/BodyTest.java
Labels: feature, priority.Medium, severity.Low

#50 Morph list command
  src/main/java/seedu/address/logic/commands/ListBodyCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ListWorkerCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniqueEntityLists.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  unused/ListFridgeCommand.java
Labels: feature, morphing, priority.High

#57 Fix bug in BodyBuilder: duplicate method
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/UpdateCommandParserTest.java
  src/test/java/seedu/address/testutil/BodyBuilder.java
Labels: type.Bug

#60 Merge fridge class
  config/travis/deploy_github_pages.sh
  src/main/java/seedu/address/model/entity/IdentificationNumber.java
  src/main/java/seedu/address/model/entity/body/Body.java
  src/main/java/seedu/address/model/entity/fridge/Fridge.java
  src/main/java/seedu/address/model/entity/fridge/FridgeStatus.java
  src/main/resources/view/StatusBarFooter.fxml
  src/test/java/seedu/address/model/entity/body/BodyTest.java
  src/test/java/seedu/address/model/entity/body/ReligionTest.java
  src/test/java/seedu/address/model/entity/fridge/FridgeStatusTest.java
  src/test/java/seedu/address/model/entity/fridge/FridgeTest.java
  src/test/java/seedu/address/testutil/BodyBuilder.java
  src/test/java/seedu/address/testutil/FridgeBuilder.java
  src/test/java/seedu/address/testutil/TypicalFridges.java
Labels: feature

#64 Add base classes for update Fridge functionality + Tests
  src/main/java/seedu/address/logic/parser/utility/UpdateFridgeDescriptor.java
  src/main/java/seedu/address/logic/parser/utility/UpdateWorkerDescriptor.java
  src/main/java/seedu/address/model/entity/Entity.java
  src/main/java/seedu/address/model/entity/body/Body.java
  src/main/java/seedu/address/model/entity/fridge/Fridge.java
  src/test/java/seedu/address/logic/parser/utility/UpdateBodyDescriptorTest.java
  src/test/java/seedu/address/logic/parser/utility/UpdateFridgeDescriptorTest.java
  src/test/java/seedu/address/logic/parser/utility/UpdateWorkerDescriptorTest.java
  src/test/java/seedu/address/model/entity/body/BodyTest.java
  src/test/java/seedu/address/model/entity/fridge/FridgeTest.java
Labels: morphing

#55 Implement abstract UndoableCommand class
  src/main/java/seedu/address/logic/commands/UndoableCommand.java
  src/test/java/seedu/address/logic/commands/UndoableCommandTest.java
Labels: feature, priority.High

#65 Implement abstract UndoableCommand class
  src/main/java/seedu/address/logic/commands/UndoableCommand.java
  src/test/java/seedu/address/logic/commands/UndoableCommandTest.java
Labels: feature

#66 Feature line chart
  src/main/java/seedu/address/model/entity/body/Body.java
  src/main/java/seedu/address/ui/LineChartPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/LineChartPanel.fxml
  src/main/resources/view/MainWindow.fxml
Labels: feature, priority.Medium

#70 Add tags for PPP linkage, update UG documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: documentation

#51 Morph EditCommand to UpdateCommand
  docs/templates/document.html.slim
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UpdateCommandParser.java
  src/main/java/seedu/address/logic/parser/utility/UpdateFridgeDescriptor.java
  src/main/java/seedu/address/model/entity/body/Body.java
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/UpdateCommandParserTest.java
  src/test/java/seedu/address/logic/parser/utility/UpdateFridgeDescriptorTest.java
Labels: feature, morphing, priority.High

#67 Update delete command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/entity/IdentificationNumber.java
  src/main/java/seedu/address/model/person/UniqueEntityLists.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalFridges.java
  src/test/java/seedu/address/testutil/TypicalUndoableCommands.java
Labels: feature, priority.High

#84 Update UserGuide for Command Specifications and Add Command
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: documentation

#77 Feature generate pdf
  build.gradle
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/GenReportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/GenReportCommandParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/storage/ReportGenerator.java
  src/test/java/seedu/address/logic/commands/GenReportCommandTest.java
  src/test/java/seedu/address/logic/parser/GenReportCommandParserTest.java
  target/classes/images/address_book_32.png
  target/classes/images/calendar.png
  target/classes/images/clock.png
  target/classes/images/fail.png
  target/classes/images/help_icon.png
  target/classes/images/info_icon.png
  target/classes/view/CommandBox.fxml
  target/classes/view/DarkTheme.css
  target/classes/view/Extensions.css
  target/classes/view/HelpWindow.fxml
  target/classes/view/MainWindow.fxml
  target/classes/view/PersonListCard.fxml
  target/classes/view/PersonListPanel.fxml
  target/classes/view/ResultDisplay.fxml
  target/classes/view/StatusBarFooter.fxml
  target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
  target/test-classes/view/UiPartTest/invalidFile.fxml
  target/test-classes/view/UiPartTest/validFile.fxml
  target/test-classes/view/UiPartTest/validFileWithFxRoot.fxml
Labels: feature, type.Story

#76 Feature Alert command
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/NotifCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/UniqueNotifsList.java
  src/main/java/seedu/address/model/notif/Notif.java
  src/main/java/seedu/address/model/notif/exceptions/DuplicateNotifException.java
  src/main/java/seedu/address/model/notif/exceptions/NotifNotFoundException.java
  src/main/java/seedu/address/model/person/UniqueEntityLists.java
  src/main/java/seedu/address/ui/BodyCard.java
  src/main/resources/view/BodyListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/NotifCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/notif/NotifTest.java
  src/test/java/seedu/address/testutil/NotifBuilder.java
  src/test/java/seedu/address/testutil/TypicalAddressBook.java
  src/test/java/seedu/address/testutil/TypicalBodies.java
  src/test/java/seedu/address/testutil/TypicalFridges.java
  src/test/java/seedu/address/testutil/TypicalNotifs.java
  src/test/java/seedu/address/testutil/TypicalUndoableCommands.java
  src/test/java/seedu/address/testutil/TypicalWorkers.java
Labels: feature, type.Story

#98 Update Ui.png
  docs/images/Ui.png
Labels: documentation

#103 Generate pdf v1.3
  docs/images/Logo.png
  src/main/java/seedu/address/storage/ReportGenerator.java
Labels: feature, priority.High, type.Story

#104 Line chart patch
  src/main/java/seedu/address/ui/LineChartPanel.java
Labels: type.Bug

#100 Alert command v1.3
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/NotifCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/utility/UpdateBodyDescriptor.java
  src/main/java/seedu/address/logic/parser/utility/UpdateFridgeDescriptor.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UniqueNotifsList.java
  src/main/java/seedu/address/model/entity/IdentificationNumber.java
  src/main/java/seedu/address/model/entity/UniqueIdentificationNumberMaps.java
  src/main/java/seedu/address/model/entity/body/Body.java
  src/main/java/seedu/address/model/entity/body/BodyStatus.java
  src/main/java/seedu/address/model/entity/fridge/Fridge.java
  src/main/java/seedu/address/model/entity/fridge/FridgeStatus.java
  src/main/java/seedu/address/model/notif/Notif.java
  src/main/java/seedu/address/model/notif/exceptions/DuplicateNotifException.java
  src/main/java/seedu/address/model/notif/exceptions/NotifNotFoundException.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/NotifWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/NotifCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/address/model/entity/IdentificationNumberTest.java
  src/test/java/seedu/address/model/entity/UniqueIdentificationNumberMapsTest.java
  src/test/java/seedu/address/model/entity/body/BodyTest.java
  src/test/java/seedu/address/model/entity/fridge/FridgeTest.java
  src/test/java/seedu/address/notif/NotifTest.java
  src/test/java/seedu/address/testutil/BodyBuilder.java
  src/test/java/seedu/address/testutil/FridgeBuilder.java
  src/test/java/seedu/address/testutil/NotifBuilder.java
  src/test/java/seedu/address/testutil/TypicalBodies.java
  src/test/java/seedu/address/testutil/TypicalFridges.java
  src/test/java/seedu/address/testutil/TypicalIdentificationNumbers.java
  src/test/java/seedu/address/testutil/TypicalNotifs.java
Labels: feature, priority.High, type.Story

#91 Implement storage for Body, Fridge and Worker
  src/main/java/seedu/address/logic/commands/UndoableCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UpdateCommandParser.java
  src/main/java/seedu/address/logic/parser/utility/UpdateBodyDescriptor.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/entity/IdentificationNumber.java
  src/main/java/seedu/address/model/entity/UniqueIdentificationNumberMaps.java
  src/main/java/seedu/address/model/entity/body/Body.java
  src/main/java/seedu/address/model/entity/fridge/Fridge.java
  src/main/java/seedu/address/model/entity/worker/Worker.java
  src/main/java/seedu/address/storage/JsonAdaptedBody.java
  src/main/java/seedu/address/storage/JsonAdaptedFridge.java
  src/main/java/seedu/address/storage/JsonAdaptedWorker.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/LineChartPanel.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/model/entity/IdentificationNumberTest.java
  src/test/java/seedu/address/model/entity/body/BodyTest.java
  src/test/java/seedu/address/model/entity/worker/WorkerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedBodyTest.java
  src/test/java/seedu/address/storage/JsonAdaptedFridgeTest.java
  src/test/java/seedu/address/storage/JsonAdaptedWorkerTest.java
  src/test/java/seedu/address/testutil/BodyBuilder.java
Labels: feature, morphing, type.Story

#113 Document undo/redo in DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/UndoSequenceDiagram.png
Labels: documentation

#119 Add DG documentation for undo/redo
  docs/DeveloperGuide.adoc
  docs/diagrams/CommandProcessActivityDiagram.puml
  docs/diagrams/UndoClassDiagram.puml
  docs/diagrams/UndoClearSequenceDiagram.puml
  docs/images/CommandProcessActivityDiagram.png
  docs/images/UndoClassDiagram.png
  docs/images/UndoClearSequenceDiagram.png
Labels: documentation

#131 Update UG
  docs/UserGuide.adoc
Labels: documentation

#134 Update DG - stats implementation
  docs/DeveloperGuide.adoc
  docs/diagrams/LineChartAddBodySequenceDiagram.puml
  docs/images/LineChartAddBodySequenceDiagram.png
Labels: documentation

#133 UG updates - filter and stats
  docs/UserGuide.adoc
Labels: documentation

#136 Update UG for AddCommand and Command Specs, updated Ui.png
  docs/UserGuide.adoc
  docs/images/Ui.png
  src/main/resources/view/MainWindow.fxml
Labels: documentation

#123 Add storage for notification
  docs/DeveloperGuide.adoc
  docs/diagrams/ChangeUiFnSequenceDiagram.puml
  docs/diagrams/NotifCommandActivityDiagram.puml
  docs/diagrams/NotifCommandSequenceDiagram.puml
  docs/images/ChangeUiFnSequenceDiagram.png
  docs/images/NotifCommandActivityDiagram.png
  docs/images/NotifCommandSequenceDiagram.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/NotifCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/model/notif/Notif.java
  src/main/java/seedu/address/storage/JsonAdaptedNotif.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedNotifTest.java
Labels: feature

#137 Update DG and update color scheme for sequence diagrams
  docs/DeveloperGuide.adoc
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/GenReportActivityDiagram.puml
  docs/diagrams/GenReportSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/style.puml
  docs/images/GenReportActivityDiagram.png
  docs/images/GenReportSequenceDiagram.png
  docs/images/Logo.png
  docs/images/logo.png
  docs/images/mortago.png
  src/main/java/seedu/address/logic/commands/GenReportCommand.java
  src/main/java/seedu/address/logic/commands/GenReportSummaryCommand.java
  src/main/java/seedu/address/logic/commands/GenReportsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/ModelManager.java.orig
  src/main/java/seedu/address/storage/ReportGenerator.java
  src/test/java/seedu/address/report/ReportGeneratorTest.java
Labels: documentation

#74 Feature filter command
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/entity/body/BodyContainsAttributesKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/entity/body/BodyContainsAttributesKeywordsPredicateTest.java
  src/test/java/seedu/address/model/entity/worker/WorkerContainsAttributesKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalBodies.java
Labels: feature, priority.Medium, status.Ongoing, testing

#128 v1.3 UndoCommand + Support for Worker Photo, Fridge Changes, Notifs
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/NotifCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/UpdateCommandParser.java
  src/main/java/seedu/address/logic/parser/utility/UpdateBodyDescriptor.java
  src/main/java/seedu/address/logic/parser/utility/UpdateEntityDescriptor.java
  src/main/java/seedu/address/logic/parser/utility/UpdateFridgeDescriptor.java
  src/main/java/seedu/address/logic/parser/utility/UpdateWorkerDescriptor.java
  src/main/java/seedu/address/model/entity/IdentificationNumber.java
  src/main/java/seedu/address/model/entity/UniqueIdentificationNumberMaps.java
  src/main/java/seedu/address/model/entity/body/Body.java
  src/main/java/seedu/address/model/entity/body/BodyContainsAttributesKeywordsPredicate.java
  src/main/java/seedu/address/model/entity/fridge/Fridge.java
  src/main/java/seedu/address/model/entity/worker/Photo.java
  src/main/java/seedu/address/model/entity/worker/Worker.java
  src/main/java/seedu/address/storage/JsonAdaptedBody.java
  src/main/java/seedu/address/storage/JsonAdaptedFridge.java
  src/main/java/seedu/address/storage/JsonAdaptedWorker.java
  src/test/data/JsonSerializableAddressBookTest/typicalMortago.json
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/NotifCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UpdateCommandParserTest.java
  src/test/java/seedu/address/logic/parser/utility/UpdateBodyDescriptorTest.java
  src/test/java/seedu/address/logic/parser/utility/UpdateWorkerDescriptorTest.java
  src/test/java/seedu/address/model/entity/IdentificationNumberTest.java
  src/test/java/seedu/address/model/entity/UniqueIdentificationNumberMapsTest.java
  src/test/java/seedu/address/model/entity/body/BodyContainsAttributesKeywordsPredicateTest.java
  src/test/java/seedu/address/model/entity/body/BodyTest.java
  src/test/java/seedu/address/model/entity/fridge/FridgeTest.java
  src/test/java/seedu/address/model/entity/worker/WorkerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedBodyTest.java
  src/test/java/seedu/address/storage/JsonAdaptedFridgeTest.java
  src/test/java/seedu/address/storage/JsonAdaptedWorkerTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/BodyBuilder.java
  src/test/java/seedu/address/testutil/ExamplePhoto.jpg
  src/test/java/seedu/address/testutil/TypicalAddressBook.java
  src/test/java/seedu/address/testutil/TypicalBodies.java
  src/test/java/seedu/address/testutil/TypicalUndoableCommands.java
  src/test/java/seedu/address/testutil/WorkerBuilder.java
  unused/Religion.java
Labels: enhancement, feature

#129 Feature line chart (more features)
  Report (ALL BODIES).pdf
  Report B00000002.pdf
  Report Summary.pdf
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/StatsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/logic/parser/StatsCommandParser.java
  src/main/java/seedu/address/ui/LineChartPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/model/entity/body/BodyTest.java
  src/test/java/seedu/address/testutil/TypicalBodies.java
  src/test/java/seedu/address/ui/LineChartPanelTest.java
Labels: enhancement, feature, priority.High

#140 Fixes #80 and #139 and made edits to UG.
  appveyor.yml
  build.gradle
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/entity/worker/Photo.java
  src/main/java/seedu/address/ui/BodyCardSelected.java
  src/main/java/seedu/address/ui/NotificationButton.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/SelectedBodyCard.fxml
  src/test/java/seedu/address/testutil/WorkerBuilder.java
Labels: documentation, type.Bug
