Repository AY1920S1-CS2103T-T13-2/main, pull requests merged in 2019-11, with the labels that each got.

#155 Generate pdf
  src/main/java/seedu/address/logic/commands/GenReportCommand.java
  src/main/java/seedu/address/logic/commands/GenReportSummaryCommand.java
  src/main/java/seedu/address/logic/commands/GenReportsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/GenReportCommandParser.java
  src/main/java/seedu/address/logic/parser/GenReportSummaryCommandParser.java
  src/main/java/seedu/address/logic/parser/GenReportsCommandParser.java
  src/main/java/seedu/address/storage/ReportGenerator.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/GenReportCommandTest.java
  src/test/java/seedu/address/logic/parser/GenReportCommandParserTest.java
  src/test/java/seedu/address/report/ReportGeneratorTest.java
Labels: feature

#225 Fixes #210, #207, #195, #190, #184, #158
  docs/UserGuide.adoc
Labels: documentation, severity.High, type.Bug

#222 Stats feature - make date not lenient (issue #175)
  src/main/java/seedu/address/logic/parser/StatsCommandParser.java
Labels: fixed, priority.High, type.Bug

#223 Make add command date not lenient (issue #205)
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: fixed, severity.High, type.Bug

#220 Fridge and Notifs Updates
  .gitignore
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/NotifCommand.java
  src/main/java/seedu/address/logic/commands/ShowNotificationsCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
Labels: type.Enhancement

#226 Fix undo bug in DeleteCommand #215, #216 errors, correct Notif bugs
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/NotifCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/UpdateCommandParser.java
  src/main/java/seedu/address/logic/parser/utility/UpdateBodyDescriptor.java
  src/test/java/seedu/address/logic/parser/UpdateCommandParserTest.java
Labels: fixed, type.Bug

#232 PPP
  Report (ALL BODIES).pdf
  Report B00000001.pdf
  Report B00000005.pdf
  Report Summary.pdf
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/GenReportActivityDiagram.puml
  docs/diagrams/GenReportSequenceDiagram.puml
  docs/diagrams/ReportGeneratorClassDiagram.puml
  docs/images/GenReportActivityDiagram.png
  docs/images/GenReportSequenceDiagram.png
  docs/images/ReportGeneratorClassDiagram.png
  docs/team/bernicechio.adoc
Labels: documentation

#233 Notifs and Redoing Bug Fixes
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/NotifCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/resources/view/WorkerListCard.fxml
Labels: severity.Medium, type.Bug

#239 Add PPP for Shao Yi
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/hongshaoyi.adoc
Labels: documentation

#253 Update PPP, UG, DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ReportGeneratorClassDiagram.puml
  docs/images/ReportGeneratorClassDiagram.png
  docs/team/bernicechio.adoc
Labels: documentation

#252 Edit UG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ChangeUiFnSequenceDiagram.puml
  docs/diagrams/NotifCommandClassDiagram.puml
  docs/images/ChangeUiFnSequenceDiagram.png
  docs/images/NotifCommandActivityDiagram.png
  docs/images/NotifCommandClassDiagram.png
  docs/images/delete-command/DeleteStep1.png
  docs/images/delete-command/DeleteStep2.png
  docs/images/delete-command/DeleteStep3.png
  docs/images/notif-command/Notif1.png
  docs/images/notif-command/Notif2.png
  docs/images/notif-command/Notif3.png
  docs/images/notif-command/Notif4.png
  docs/images/notif-command/Notif5.png
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/NotifCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/UpdateCommandParser.java
  src/main/java/seedu/address/model/notif/Notif.java
  src/test/java/seedu/address/logic/commands/NotifCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
Labels: documentation

#288 Update PPP, UGDG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/PhotoActivityDiagram.puml
  docs/images/PhotoActivityDiagram.png
  docs/team/shaoyi1997.adoc
Labels: documentation
